/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activity
         * @description Merged, reverse-chronological activity across incidents, proposals and
         *     contract approvals.
         */
        get: operations["list_activity_api_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/badge/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status Badge
         * @description Read-only Compliance-Badge. format=svg (default) | json.
         */
        get: operations["status_badge_api_badge__product__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{dataset}/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry Run Checks
         * @description Compile contract for dataset and run checks without persisting results.
         *
         *     Body: { "environment": "<env-name>", "execution_mode": "auto|batch|isolated" }
         *     Ohne Environment: compile-only preview. Ergebnisse werden NIE persistiert.
         */
        post: operations["dry_run_checks_api_checks__dataset__dry_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{dataset}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revert Checks
         * @description [AUTHZ] Revert checks/{dataset}/checks.yml to the previous git version (F7).
         */
        post: operations["revert_checks_api_checks__dataset__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Contracts
         * @description A3: Liste aus contract_index — Git ist keine Query-DB. `guarantees`
         *     ist hier leer; das volle Contract liefert GET /api/contracts/{product}.
         */
        get: operations["list_contracts_api_contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reindex Contracts
         * @description Index-Rebuild nach externen Änderungen (git pull) — steward+.
         */
        post: operations["reindex_contracts_api_contracts_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract */
        get: operations["get_contract_api_contracts__product__get"];
        /**
         * Update Contract
         * @description [CONTRACT-SQL-FREE] [AUTHZ] Update a contract — Gate G1 enforced here.
         *
         *     Lifecycle ist kein Eingabefeld: das Ergebnis eines PUT ist IMMER ein Draft.
         *     Ein PUT auf einen aktiven Contract erzeugt damit ein Draft-Amendment — die
         *     zertifizierte Version bleibt als `.active.yml`-Snapshot die G3-Diff-Basis,
         *     bis ein erneutes Approve sie ersetzt.
         */
        put: operations["update_contract_api_contracts__product__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Contract
         * @description [AUTHZ] Promote a draft contract to active (WS2-6 / M2).
         *
         *     Server-side breaking guard (G3): if the change is breaking versus the last
         *     certified version, a SemVer **major** bump is required.
         */
        post: operations["approve_contract_api_contracts__product__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Contract
         * @description [DETERMINISM] [SCHEMA-MAP] Compile contract → CheckDefs.
         *
         *     G1: der Contract wird auch auf dem Disk-Pfad validiert (kein Schmuggel an
         *     PUT vorbei). G2: '{schema}' bleibt als Platzhalter im Output. Non-dry-run
         *     erfordert lifecycle=active (WS3-2) und Schreibrecht.
         */
        post: operations["compile_contract_api_contracts__product__compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/deprecate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deprecate Contract
         * @description [AUTHZ] Retire an active contract (WS2-6).
         */
        post: operations["deprecate_contract_api_contracts__product__deprecate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diff Contract
         * @description Compare submitted contract against current version (WS2-4).
         */
        post: operations["diff_contract_api_contracts__product__diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/export/bdc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Bdc
         * @description Generate CSN + ORD artifact fragments for BDC integration. (WS5-4)
         *
         *     Einseitig (E1): files are returned as JSON for manual deployment.
         *     Never writes to DB or catalog.
         */
        post: operations["export_bdc_api_contracts__product__export_bdc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/export/odcs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Odcs
         * @description R5-1: ODCS-3.1-Export (Bitol) — Interop mit OpenMetadata/Collibra/
         *     datacontract-cli/Soda. Einweg; Compliance bleibt draußen (A1).
         */
        get: operations["export_odcs_api_contracts__product__export_odcs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Contract
         * @description [AUTHZ] Seed a draft contract from the inventory object (WS2-2).
         */
        post: operations["seed_contract_api_contracts__product__seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/sla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contract Sla
         * @description R4-3: SLA-Compliance über Zeitfenster — %-compliant aus dem
         *     Compliance-Event-Log, nicht nur Letzter-Lauf-Zustand.
         */
        get: operations["get_contract_sla_api_contracts__product__sla_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/version-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version Diff Contract
         * @description UX-N13: semantic diff of the working contract against the last certified
         *     version (`.active.yml`). Reuses the breaking-change engine so the FE can
         *     explain the *meaning* of each change, not just two code spans.
         */
        get: operations["version_diff_contract_api_contracts__product__version_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Trend
         * @description UX-N12: data-health trend for the cockpit gauge — share of datasets
         *     passing their latest run vs. one run earlier.
         */
        get: operations["health_trend_api_coverage_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status Heatmap
         * @description UX-N10: object × day reliability heatmap (worst run status per day).
         */
        get: operations["status_heatmap_api_coverage_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage Summary */
        get: operations["coverage_summary_api_coverage_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasphere/data-loads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Data Loads
         * @description List recent data loads (task chains + replication flows) across all objects.
         */
        get: operations["list_data_loads_api_datasphere_data_loads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasphere/data-loads/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Object Data Loads
         * @description List recent data loads for a specific Datasphere object.
         */
        get: operations["get_object_data_loads_api_datasphere_data_loads__object_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Environments
         * @description Environment-Namen für den RunTriggerDialog — NIE Credentials (S-13).
         */
        get: operations["list_environments_api_environments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Extract
         * @description Reload inventory/lineage snapshots and report counts.
         *
         *     F5: In local mode, touch the snapshot files to reset the staleness clock
         *     (production deployments would call the real analyzer chain here). Either
         *     way, the response includes the new extraction timestamp so the frontend
         *     can update the staleness indicator immediately.
         */
        post: operations["trigger_extract_api_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Failing Checks
         * @description Derived view: breached check results within last 7 days (not a separate store).
         */
        get: operations["list_failing_checks_api_incidents_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_api_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transition Incident
         * @description [AUTHZ] Statuswechsel/Assign/Note — jede Aktion landet in der Timeline.
         */
        post: operations["transition_incident_api_incidents__incident_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Inventory
         * @description Object/column picker source for the ContractEditor autocomplete (U2).
         */
        get: operations["list_inventory_api_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library */
        get: operations["get_library_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lineage Graph */
        get: operations["get_lineage_graph_api_lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service Health Metrics
         * @description Self-observability: request counters, uptime, latency percentiles (JSON).
         */
        get: operations["service_health_metrics_api_metrics_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Objects */
        get: operations["list_objects_api_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object */
        get: operations["get_object_api_objects__object_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/checks/{check_name}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Check History
         * @description WS1-2: actual_value-Zeitreihe je Check — Sparkline- und Miner-Quelle.
         */
        get: operations["get_check_history_api_objects__object_id__checks__check_name__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Run
         * @description Trigger a DQ run for an object. Returns run_id immediately (202). [ENGINE-FROZEN]
         *
         *     [AUTHZ] Runs lösen Last auf HANA aus — viewer darf nicht triggern.
         *     [SCHEMA-MAP] '{schema}' aus kompilierten Checks wird HIER gebunden (G2):
         *     aus dem Environment, sonst aus dem Inventar-Schema des Objekts.
         */
        post: operations["trigger_run_api_objects__object_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object Runs */
        get: operations["get_object_runs_api_objects__object_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Object Timeseries
         * @description UX-N1: Freshness-/Volume-Zeitreihen je Objekt mit erwartetem Baseline-Band
         *     (Mean ± 3σ aus `dq_baselines`) und Anomalie-Markern. Macht aus dem
         *     Status-Board ein Monitoring-Tool.
         */
        get: operations["get_object_timeseries_api_objects__object_id__timeseries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Proposals
         * @description Mine proposals; overlay persisted steward decisions. Filter via ?status=open.
         */
        get: operations["list_proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Proposal
         * @description [AUTHZ] Accept a proposal — creates a draft contract amendment. No auto-apply (WS5-2).
         */
        post: operations["accept_proposal_api_proposals__proposal_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Proposal */
        post: operations["reject_proposal_api_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snooze Proposal */
        post: operations["snooze_proposal_api_proposals__proposal_id__snooze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Runs
         * @description UX-N5: regression diff of two runs — per-check status transitions
         *     (newly red vs. recovered). Server-authoritative so the FE only renders.
         */
        get: operations["compare_runs_api_runs_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Diagnostics
         * @description [PII-GATE] Diagnostik-Zeilen (bereits allowlist-projiziert persistiert).
         *
         *     Defense-in-depth: Rohzeilen-Sicht erfordert steward+ — viewer sieht
         *     Skalare, nie Datensätze.
         */
        get: operations["get_run_diagnostics_api_runs__run_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Events
         * @description Polling fallback for SSE (A5): returns persisted progress lines.
         */
        get: operations["get_run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Results
         * @description WS1-2: nur die Check-Ergebnisse eines Runs (ohne Run-Header).
         */
        get: operations["get_run_results_api_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description SSE für einen Run — Store-getrieben, multi-worker-fest (F2/A5).
         *
         *     Polling-Fallback mit identischem Inhalt: /api/runs/{id}/events.
         */
        get: operations["stream_events_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityItem */
        ActivityItem: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /** At */
            at: string;
            /** Kind */
            kind: string;
            /** Product */
            product: string;
            /** Ref */
            ref: string;
            /** Summary */
            summary: string;
        };
        /** CheckDefOut */
        CheckDefOut: {
            /** Expect */
            expect: string;
            /** Name */
            name: string;
            /**
             * Owned By
             * @default platform
             */
            owned_by: string;
            /** Severity */
            severity: string;
            /** Sql */
            sql: string;
            /**
             * Type
             * @default
             */
            type: string;
            /**
             * Unit
             * @default
             */
            unit: string;
        };
        /** CheckResultOut */
        CheckResultOut: {
            /** Actual Value */
            actual_value?: string | null;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Error */
            error?: string | null;
            /**
             * Expect
             * @default
             */
            expect: string;
            /** Name */
            name: string;
            /**
             * Passed
             * @default false
             */
            passed: boolean;
            /**
             * Severity
             * @default fail
             */
            severity: string;
            /**
             * Sql
             * @default
             */
            sql: string;
            /**
             * State
             * @default executed
             */
            state: string;
            /**
             * Type
             * @default
             */
            type: string;
        };
        /** CompileOut */
        CompileOut: {
            /**
             * Checks
             * @default []
             */
            checks: components["schemas"]["CheckDefOut"][];
            /**
             * Conflicts
             * @default []
             */
            conflicts: string[];
            /** Dataset */
            dataset: string;
            /**
             * Determinism Hash
             * @default
             */
            determinism_hash: string;
            /** Product */
            product: string;
            /**
             * Yaml Preview
             * @default
             */
            yaml_preview: string;
        };
        /**
         * ContractIn
         * @description Lifecycle ist bewusst KEIN Eingabefeld — Übergänge laufen nur über
         *     approve/deprecate; PUT erzwingt draft (S-2).
         */
        ContractIn: {
            /**
             * Dataset
             * @default
             */
            dataset: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Guarantees
             * @default {}
             */
            guarantees: {
                [key: string]: unknown;
            };
            /**
             * Owned By
             * @default platform
             */
            owned_by: string;
            /**
             * Owners
             * @default []
             */
            owners: string[];
            /** Product */
            product: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /** ContractOut */
        ContractOut: {
            /** Compliance */
            compliance?: string | null;
            /**
             * Dataset
             * @default
             */
            dataset: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Guarantees
             * @default {}
             */
            guarantees: {
                [key: string]: unknown;
            };
            /**
             * Lifecycle
             * @default draft
             */
            lifecycle: string;
            /**
             * Owned By
             * @default platform
             */
            owned_by: string;
            /**
             * Owners
             * @default []
             */
            owners: string[];
            /** Product */
            product: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /** DataLoadOut */
        DataLoadOut: {
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Load Type */
            load_type: string;
            /** Object Id */
            object_id: string;
            /**
             * Raw
             * @default {}
             */
            raw: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status?: string | null;
            /** Triggered By */
            triggered_by?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentTransitionIn */
        IncidentTransitionIn: {
            /**
             * Note
             * @default
             */
            note: string;
            /** Owner */
            owner?: string | null;
            /** Status */
            status?: string | null;
        };
        /** ObjectDetailOut */
        ObjectDetailOut: {
            /**
             * Check Count
             * @default 0
             */
            check_count: number;
            /** Contract */
            contract?: {
                [key: string]: unknown;
            } | null;
            /**
             * Contract Status
             * @default
             */
            contract_status: string;
            /**
             * Cov Flag
             * @default out_of_scope
             */
            cov_flag: string;
            /**
             * Family
             * @default quality
             */
            family: string;
            /**
             * Family Status
             * @default {
             *       "observability": "unknown",
             *       "quality": "unknown"
             *     }
             */
            family_status: {
                [key: string]: string;
            };
            /** Id */
            id: string;
            /** Last Run */
            last_run?: string | null;
            /** Last Run Id */
            last_run_id?: string | null;
            latest_run?: components["schemas"]["RunSummaryOut"] | null;
            /**
             * Layer
             * @default
             */
            layer: string;
            /** Name */
            name: string;
            /**
             * Owned By
             * @default platform
             */
            owned_by: string;
            /**
             * Run History
             * @default []
             */
            run_history: components["schemas"]["RunListItem"][];
            /**
             * Schema Name
             * @default
             */
            schema_name: string;
            /**
             * Space
             * @default
             */
            space: string;
            /**
             * Status
             * @default unknown
             */
            status: string;
        };
        /** ObjectOut */
        ObjectOut: {
            /**
             * Check Count
             * @default 0
             */
            check_count: number;
            /**
             * Contract Status
             * @default
             */
            contract_status: string;
            /**
             * Cov Flag
             * @default out_of_scope
             */
            cov_flag: string;
            /**
             * Family
             * @default quality
             */
            family: string;
            /**
             * Family Status
             * @default {
             *       "observability": "unknown",
             *       "quality": "unknown"
             *     }
             */
            family_status: {
                [key: string]: string;
            };
            /** Id */
            id: string;
            /** Last Run */
            last_run?: string | null;
            /** Last Run Id */
            last_run_id?: string | null;
            /**
             * Layer
             * @default
             */
            layer: string;
            /** Name */
            name: string;
            /**
             * Owned By
             * @default platform
             */
            owned_by: string;
            /**
             * Schema Name
             * @default
             */
            schema_name: string;
            /**
             * Space
             * @default
             */
            space: string;
            /**
             * Status
             * @default unknown
             */
            status: string;
        };
        /** ProposalOut */
        ProposalOut: {
            /** Check Name */
            check_name: string;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Current Expect
             * @default
             */
            current_expect: string;
            /** Id */
            id: string;
            /** Product */
            product: string;
            /** Proposed Expect */
            proposed_expect: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Stats
             * @default {}
             */
            stats: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @default open
             */
            status: string;
        };
        /** RunListItem */
        RunListItem: {
            /** Dataset */
            dataset: string;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Finished At
             * @default
             */
            finished_at: string;
            /**
             * Overall Status
             * @default pass
             */
            overall_status: string;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /** Run Id */
            run_id: string;
            /**
             * Run State
             * @default finished
             */
            run_state: string;
            /**
             * Started At
             * @default
             */
            started_at: string;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Triggered By
             * @default manual
             */
            triggered_by: string;
            /**
             * Warnings
             * @default 0
             */
            warnings: number;
        };
        /** RunSummaryOut */
        RunSummaryOut: {
            /**
             * Actor
             * @default
             */
            actor: string;
            /**
             * Contract Hash
             * @default
             */
            contract_hash: string;
            /**
             * Contract Version
             * @default
             */
            contract_version: string;
            /** Dataset */
            dataset: string;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Finished At
             * @default
             */
            finished_at: string;
            /**
             * Overall Status
             * @default pass
             */
            overall_status: string;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["CheckResultOut"][];
            /** Run Id */
            run_id: string;
            /**
             * Run State
             * @default finished
             */
            run_state: string;
            /**
             * Schema Name
             * @default
             */
            schema_name: string;
            /**
             * Started At
             * @default
             */
            started_at: string;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Triggered By
             * @default manual
             */
            triggered_by: string;
            /**
             * Warnings
             * @default 0
             */
            warnings: number;
        };
        /** RunTriggerIn */
        RunTriggerIn: {
            /**
             * Environment
             * @default
             */
            environment: string;
            /**
             * Execution Mode
             * @default auto
             */
            execution_mode: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_activity_api_activity_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_badge_api_badge__product__get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dry_run_checks_api_checks__dataset__dry_run_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_checks_api_checks__dataset__revert_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contracts_api_contracts_get: {
        parameters: {
            query?: {
                lifecycle?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_contracts_api_contracts_reindex_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_api_contracts__product__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contract_api_contracts__product__put: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_contract_api_contracts__product__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_contract_api_contracts__product__compile_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deprecate_contract_api_contracts__product__deprecate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_contract_api_contracts__product__diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_bdc_api_contracts__product__export_bdc_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_odcs_api_contracts__product__export_odcs_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_contract_api_contracts__product__seed_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_sla_api_contracts__product__sla_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_diff_contract_api_contracts__product__version_diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_trend_api_coverage_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    status_heatmap_api_coverage_heatmap_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coverage_summary_api_coverage_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_data_loads_api_datasphere_data_loads_get: {
        parameters: {
            query?: {
                /** @description Datasphere space ID */
                space?: string | null;
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataLoadOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_data_loads_api_datasphere_data_loads__object_id__get: {
        parameters: {
            query?: {
                /** @description Datasphere space ID */
                space?: string | null;
                top?: number;
            };
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataLoadOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_environments_api_environments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_extract_api_extract_post: {
        parameters: {
            query?: {
                environment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_incidents_api_incidents_get: {
        parameters: {
            query?: {
                status?: string | null;
                severity?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_failing_checks_api_incidents_checks_get: {
        parameters: {
            query?: {
                severity?: string | null;
                dataset?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_api_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_incident_api_incidents__incident_id__transition_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                incident_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentTransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inventory_api_inventory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_library_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_lineage_graph_api_lineage_get: {
        parameters: {
            query?: {
                space?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    service_health_metrics_api_metrics_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_objects_api_objects_get: {
        parameters: {
            query?: {
                space?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_api_objects__object_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_check_history_api_objects__object_id__checks__check_name__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                object_id: string;
                check_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_run_api_objects__object_id__run_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunTriggerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_runs_api_objects__object_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_timeseries_api_objects__object_id__timeseries_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_proposals_get: {
        parameters: {
            query?: {
                dataset?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_proposal_api_proposals__proposal_id__accept_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_api_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snooze_proposal_api_proposals__proposal_id__snooze_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_runs_api_runs_compare_get: {
        parameters: {
            query: {
                /** @description Baseline run_id (earlier) */
                base: string;
                /** @description Comparison run_id (later) */
                head: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_diagnostics_api_runs__run_id__diagnostics_get: {
        parameters: {
            query?: {
                check_name?: string | null;
            };
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_results_api_runs__run_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_stream_get: {
        parameters: {
            query: {
                run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
