/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/badge/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Badge */
        get: operations["badge_api_badge__product__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{dataset}/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry Run Checks
         * @description Compile contract for dataset and run checks without persisting results.
         *
         *     Body: { "environment": "<env-name>", "execution_mode": "auto|batch|isolated" }
         *     Ohne Environment: compile-only preview. Ergebnisse werden NIE persistiert.
         */
        post: operations["dry_run_checks_api_checks__dataset__dry_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checks/{dataset}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revert Checks
         * @description [AUTHZ] Revert checks/{dataset}/checks.yml to the previous git version (F7).
         */
        post: operations["revert_checks_api_checks__dataset__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contracts */
        get: operations["list_contracts_api_contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contract */
        get: operations["get_contract_api_contracts__product__get"];
        /**
         * Update Contract
         * @description [CONTRACT-SQL-FREE] [AUTHZ] Update a contract — Gate G1 enforced here.
         *
         *     Lifecycle ist kein Eingabefeld: das Ergebnis eines PUT ist IMMER ein Draft.
         *     Ein PUT auf einen aktiven Contract erzeugt damit ein Draft-Amendment — die
         *     zertifizierte Version bleibt als `.active.yml`-Snapshot die G3-Diff-Basis,
         *     bis ein erneutes Approve sie ersetzt.
         */
        put: operations["update_contract_api_contracts__product__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Contract
         * @description [AUTHZ] Promote a draft contract to active (WS2-6 / M2).
         *
         *     Server-side breaking guard (G3): if the change is breaking versus the last
         *     certified version, a SemVer **major** bump is required.
         */
        post: operations["approve_contract_api_contracts__product__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Contract
         * @description [DETERMINISM] [SCHEMA-MAP] Compile contract → CheckDefs.
         *
         *     G1: der Contract wird auch auf dem Disk-Pfad validiert (kein Schmuggel an
         *     PUT vorbei). G2: '{schema}' bleibt als Platzhalter im Output. Non-dry-run
         *     erfordert lifecycle=active (WS3-2) und Schreibrecht.
         */
        post: operations["compile_contract_api_contracts__product__compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/deprecate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deprecate Contract
         * @description [AUTHZ] Retire an active contract (WS2-6).
         */
        post: operations["deprecate_contract_api_contracts__product__deprecate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diff Contract
         * @description Compare submitted contract against current version (WS2-4).
         */
        post: operations["diff_contract_api_contracts__product__diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/export/bdc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Bdc
         * @description Generate CSN + ORD artifact fragments for BDC integration. (WS5-4)
         *
         *     Einseitig (E1): files are returned as JSON for manual deployment.
         *     Never writes to DB or catalog.
         */
        post: operations["export_bdc_api_contracts__product__export_bdc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/export/odcs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Odcs
         * @description R5-1: deterministic ODCS 3.1 export. [A1] compliance stays out.
         */
        get: operations["export_odcs_api_contracts__product__export_odcs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Contract
         * @description [AUTHZ] Seed a draft contract from the inventory object (WS2-2).
         */
        post: operations["seed_contract_api_contracts__product__seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{product}/sla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sla
         * @description R4-3: % of the window the contract spent non-breached (status-page style).
         */
        get: operations["get_sla_api_contracts__product__sla_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage Summary */
        get: operations["coverage_summary_api_coverage_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Extract
         * @description Reload inventory/lineage snapshots and report counts (analyzer placeholder).
         */
        post: operations["trigger_extract_api_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Incidents
         * @description R4-1 Inbox: incidents from the lifecycle table, severity-sorted.
         */
        get: operations["list_incidents_api_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_api_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Incident
         * @description [AUTHZ] Assign an owner — steward role or higher.
         */
        post: operations["assign_incident_api_incidents__incident_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transition Incident
         * @description [AUTHZ] Acknowledge/investigate/resolve — steward role or higher.
         */
        post: operations["transition_incident_api_incidents__incident_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Inventory
         * @description Object/column picker source for the ContractEditor autocomplete (U2).
         */
        get: operations["list_inventory_api_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library */
        get: operations["get_library_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lineage Graph */
        get: operations["get_lineage_graph_api_lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Objects */
        get: operations["list_objects_api_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object */
        get: operations["get_object_api_objects__object_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/checks/{check_name}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Check History
         * @description WS1-2: actual_value-Zeitreihe je Check — Sparkline- und Miner-Quelle.
         */
        get: operations["get_check_history_api_objects__object_id__checks__check_name__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Run
         * @description Trigger a DQ run for an object. Returns run_id immediately (202). [ENGINE-FROZEN]
         *
         *     [AUTHZ] Runs lösen Last auf HANA aus — viewer darf nicht triggern.
         *     [SCHEMA-MAP] '{schema}' aus kompilierten Checks wird HIER gebunden (G2):
         *     aus dem Environment, sonst aus dem Inventar-Schema des Objekts.
         */
        post: operations["trigger_run_api_objects__object_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Object Runs */
        get: operations["get_object_runs_api_objects__object_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Proposals
         * @description Mine proposals; overlay persisted steward decisions. Filter via ?status=open.
         */
        get: operations["list_proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Proposal
         * @description [AUTHZ] Accept a proposal — creates a draft contract amendment. No auto-apply (WS5-2).
         */
        post: operations["accept_proposal_api_proposals__proposal_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Proposal */
        post: operations["reject_proposal_api_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snooze Proposal */
        post: operations["snooze_proposal_api_proposals__proposal_id__snooze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Diagnostics
         * @description R2-6/[PII-GATE]: diagnostic rows persisted for a run. Already projected
         *     to the allowlist at write time — no raw column leaks here.
         */
        get: operations["get_run_diagnostics_api_runs__run_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Events
         * @description Polling fallback for SSE (A5): returns persisted progress lines.
         */
        get: operations["get_run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Results
         * @description R2-6: check results of a run (without the run envelope).
         */
        get: operations["get_run_results_api_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description SSE für einen Run — Store-getrieben, multi-worker-fest (F2/A5).
         *
         *     Polling-Fallback mit identischem Inhalt: /api/runs/{id}/events.
         */
        get: operations["stream_events_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckDefOut */
        CheckDefOut: {
            /** Expect */
            expect: string;
            /** Name */
            name: string;
            /**
             * Owned By
             * @default platform
             */
            owned_by: string;
            /** Severity */
            severity: string;
            /** Sql */
            sql: string;
            /**
             * Type
             * @default
             */
            type: string;
            /**
             * Unit
             * @default
             */
            unit: string;
        };
        /** CheckResultOut */
        CheckResultOut: {
            /** Actual Value */
            actual_value?: string | null;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Error */
            error?: string | null;
            /**
             * Expect
             * @default
             */
            expect: string;
            /** Name */
            name: string;
            /**
             * Passed
             * @default false
             */
            passed: boolean;
            /**
             * Severity
             * @default fail
             */
            severity: string;
            /**
             * Sql
             * @default
             */
            sql: string;
            /**
             * State
             * @default executed
             */
            state: string;
        };
        /** CompileOut */
        CompileOut: {
            /**
             * Checks
             * @default []
             */
            checks: components["schemas"]["CheckDefOut"][];
            /**
             * Conflicts
             * @default []
             */
            conflicts: string[];
            /** Dataset */
            dataset: string;
            /**
             * Determinism Hash
             * @default
             */
            determinism_hash: string;
            /** Product */
            product: string;
            /**
             * Yaml Preview
             * @default
             */
            yaml_preview: string;
        };
        /**
         * ContractIn
         * @description Lifecycle ist bewusst KEIN Eingabefeld — Übergänge laufen nur über
         *     approve/deprecate; PUT erzwingt draft (S-2).
         */
        ContractIn: {
            /**
             * Dataset
             * @default
             */
            dataset: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Guarantees
             * @default {}
             */
            guarantees: {
                [key: string]: unknown;
            };
            /**
             * Owned By
             * @default platform
             */
            owned_by: string;
            /**
             * Owners
             * @default []
             */
            owners: string[];
            /** Product */
            product: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /** ContractOut */
        ContractOut: {
            /** Compliance */
            compliance?: string | null;
            /**
             * Dataset
             * @default
             */
            dataset: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Guarantees
             * @default {}
             */
            guarantees: {
                [key: string]: unknown;
            };
            /**
             * Lifecycle
             * @default draft
             */
            lifecycle: string;
            /**
             * Owned By
             * @default platform
             */
            owned_by: string;
            /**
             * Owners
             * @default []
             */
            owners: string[];
            /** Product */
            product: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /** FamilyStatus */
        FamilyStatus: {
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Status
             * @default unknown
             */
            status: string;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentAssignIn */
        IncidentAssignIn: {
            /** Owner */
            owner: string;
        };
        /** IncidentDetailOut */
        IncidentDetailOut: {
            /**
             * Check Name
             * @default
             */
            check_name: string;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["IncidentEventOut"][];
            /** Id */
            id: string;
            /**
             * Opened At
             * @default
             */
            opened_at: string;
            /**
             * Owner
             * @default
             */
            owner: string;
            /** Product */
            product: string;
            /**
             * Resolved At
             * @default
             */
            resolved_at: string;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /**
             * Severity
             * @default fail
             */
            severity: string;
            /**
             * Status
             * @default open
             */
            status: string;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** IncidentEventOut */
        IncidentEventOut: {
            /**
             * Actor
             * @default
             */
            actor: string;
            /**
             * At
             * @default
             */
            at: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Kind */
            kind: string;
        };
        /** IncidentOut */
        IncidentOut: {
            /**
             * Check Name
             * @default
             */
            check_name: string;
            /** Id */
            id: string;
            /**
             * Opened At
             * @default
             */
            opened_at: string;
            /**
             * Owner
             * @default
             */
            owner: string;
            /** Product */
            product: string;
            /**
             * Resolved At
             * @default
             */
            resolved_at: string;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /**
             * Severity
             * @default fail
             */
            severity: string;
            /**
             * Status
             * @default open
             */
            status: string;
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** IncidentTransitionIn */
        IncidentTransitionIn: {
            /**
             * Note
             * @default
             */
            note: string;
            /** Status */
            status: string;
        };
        /** ObjectDetailOut */
        ObjectDetailOut: {
            /**
             * Check Count
             * @default 0
             */
            check_count: number;
            /** Contract */
            contract?: {
                [key: string]: unknown;
            } | null;
            /**
             * Contract Status
             * @default
             */
            contract_status: string;
            /**
             * Cov Flag
             * @default out_of_scope
             */
            cov_flag: string;
            /**
             * Families
             * @default {}
             */
            families: {
                [key: string]: components["schemas"]["FamilyStatus"];
            };
            /**
             * Family
             * @default quality
             */
            family: string;
            /** Id */
            id: string;
            /** Last Run */
            last_run?: string | null;
            /** Last Run Id */
            last_run_id?: string | null;
            latest_run?: components["schemas"]["RunSummaryOut"] | null;
            /**
             * Layer
             * @default
             */
            layer: string;
            /** Name */
            name: string;
            /**
             * Owned By
             * @default platform
             */
            owned_by: string;
            /**
             * Run History
             * @default []
             */
            run_history: components["schemas"]["RunListItem"][];
            /**
             * Schema Name
             * @default
             */
            schema_name: string;
            /**
             * Space
             * @default
             */
            space: string;
            /**
             * Status
             * @default unknown
             */
            status: string;
        };
        /** ObjectOut */
        ObjectOut: {
            /**
             * Check Count
             * @default 0
             */
            check_count: number;
            /**
             * Contract Status
             * @default
             */
            contract_status: string;
            /**
             * Cov Flag
             * @default out_of_scope
             */
            cov_flag: string;
            /**
             * Families
             * @default {}
             */
            families: {
                [key: string]: components["schemas"]["FamilyStatus"];
            };
            /**
             * Family
             * @default quality
             */
            family: string;
            /** Id */
            id: string;
            /** Last Run */
            last_run?: string | null;
            /** Last Run Id */
            last_run_id?: string | null;
            /**
             * Layer
             * @default
             */
            layer: string;
            /** Name */
            name: string;
            /**
             * Owned By
             * @default platform
             */
            owned_by: string;
            /**
             * Schema Name
             * @default
             */
            schema_name: string;
            /**
             * Space
             * @default
             */
            space: string;
            /**
             * Status
             * @default unknown
             */
            status: string;
        };
        /** ProposalOut */
        ProposalOut: {
            /** Check Name */
            check_name: string;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Current Expect
             * @default
             */
            current_expect: string;
            /** Id */
            id: string;
            /** Product */
            product: string;
            /** Proposed Expect */
            proposed_expect: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Stats
             * @default {}
             */
            stats: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @default open
             */
            status: string;
        };
        /** RunListItem */
        RunListItem: {
            /** Dataset */
            dataset: string;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Finished At
             * @default
             */
            finished_at: string;
            /**
             * Overall Status
             * @default pass
             */
            overall_status: string;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /** Run Id */
            run_id: string;
            /**
             * Run State
             * @default finished
             */
            run_state: string;
            /**
             * Started At
             * @default
             */
            started_at: string;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Triggered By
             * @default manual
             */
            triggered_by: string;
            /**
             * Warnings
             * @default 0
             */
            warnings: number;
        };
        /** RunSummaryOut */
        RunSummaryOut: {
            /**
             * Actor
             * @default
             */
            actor: string;
            /**
             * Contract Hash
             * @default
             */
            contract_hash: string;
            /**
             * Contract Version
             * @default
             */
            contract_version: string;
            /** Dataset */
            dataset: string;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Finished At
             * @default
             */
            finished_at: string;
            /**
             * Overall Status
             * @default pass
             */
            overall_status: string;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["CheckResultOut"][];
            /** Run Id */
            run_id: string;
            /**
             * Run State
             * @default finished
             */
            run_state: string;
            /**
             * Schema Name
             * @default
             */
            schema_name: string;
            /**
             * Started At
             * @default
             */
            started_at: string;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Triggered By
             * @default manual
             */
            triggered_by: string;
            /**
             * Warnings
             * @default 0
             */
            warnings: number;
        };
        /** RunTriggerIn */
        RunTriggerIn: {
            /**
             * Environment
             * @default
             */
            environment: string;
            /**
             * Execution Mode
             * @default auto
             */
            execution_mode: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    badge_api_badge__product__get: {
        parameters: {
            query?: {
                format?: string;
                token?: string;
            };
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dry_run_checks_api_checks__dataset__dry_run_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_checks_api_checks__dataset__revert_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contracts_api_contracts_get: {
        parameters: {
            query?: {
                lifecycle?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_api_contracts__product__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contract_api_contracts__product__put: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_contract_api_contracts__product__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_contract_api_contracts__product__compile_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deprecate_contract_api_contracts__product__deprecate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_contract_api_contracts__product__diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_bdc_api_contracts__product__export_bdc_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_odcs_api_contracts__product__export_odcs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_contract_api_contracts__product__seed_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sla_api_contracts__product__sla_get: {
        parameters: {
            query?: {
                window_days?: number;
            };
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coverage_summary_api_coverage_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_extract_api_extract_post: {
        parameters: {
            query?: {
                environment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_incidents_api_incidents_get: {
        parameters: {
            query?: {
                status?: string | null;
                severity?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_api_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_incident_api_incidents__incident_id__assign_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentAssignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_incident_api_incidents__incident_id__transition_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentTransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inventory_api_inventory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_library_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_lineage_graph_api_lineage_get: {
        parameters: {
            query?: {
                space?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_objects_api_objects_get: {
        parameters: {
            query?: {
                space?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_api_objects__object_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_check_history_api_objects__object_id__checks__check_name__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                object_id: string;
                check_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_run_api_objects__object_id__run_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunTriggerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_runs_api_objects__object_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_proposals_get: {
        parameters: {
            query?: {
                dataset?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_proposal_api_proposals__proposal_id__accept_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_api_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snooze_proposal_api_proposals__proposal_id__snooze_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DQ-Role"?: string | null;
                authorization?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_diagnostics_api_runs__run_id__diagnostics_get: {
        parameters: {
            query?: {
                check_name?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_results_api_runs__run_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_stream_get: {
        parameters: {
            query: {
                run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
