from typing import Protocol, List, Optional, runtime_checkable
from dq_core.engine.models import RunSummary


@runtime_checkable
class ResultStoreProtocol(Protocol):
    def save_run(self, summary: RunSummary) -> None: ...
    def get_run_detail(self, run_id: str) -> Optional[dict]: ...
    def get_latest_run(self, dataset: str) -> Optional[dict]: ...
    def get_history(self, dataset: str, limit: int = 10) -> List[dict]: ...
    def get_previous_actuals(self, dataset: str, check_name: str, limit: int = 10) -> List[dict]: ...
    def get_diagnostics(self, run_id: str, check_name: str) -> List[dict]: ...
    def list_runs(self, limit: int = 50) -> List[dict]: ...
    def get_object_status(self) -> List[dict]: ...
    def update_run_state(self, run_id: str, state: str) -> None: ...
    def save_compliance(self, product: str, contract_version: str, compliance: str, last_run_id: str) -> None: ...
    def get_compliance(self, product: str) -> Optional[dict]: ...
    def list_contracts(self) -> List[dict]: ...
    def upsert_contract_index(self, product: str, lifecycle: str, owned_by: str, version: str, head_hash: str) -> None: ...
    def save_proposal(self, proposal: dict) -> None: ...
    def list_proposals(self, status: str = "open") -> List[dict]: ...
    def update_proposal_status(self, proposal_id: str, status: str) -> None: ...
    def close(self) -> None: ...
