from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ..engine.models import RunSummary


@runtime_checkable
class ResultStoreProtocol(Protocol):
    """Abstract interface for all result-store backends (SQLite, HANA, …)."""

    def save_run(self, summary: RunSummary) -> None: ...

    def get_run(self, run_id: str) -> dict[str, Any] | None: ...

    def get_runs(self, dataset: str, limit: int = 100) -> list[dict[str, Any]]: ...

    def get_previous_actuals(self, dataset: str) -> dict[str, str]: ...

    def get_check_history(self, dataset: str, check_name: str, limit: int = 50) -> list[dict[str, Any]]: ...

    def set_run_state(self, run_id: str, state: str, finished_at: str | None = None) -> None: ...

    def get_compliance(self, product: str) -> dict[str, Any] | None: ...

    def set_compliance(self, product: str, version: str, compliance: str, run_id: str) -> None: ...

    def get_diagnostics(self, run_id: str, check_name: str | None = None) -> list[dict[str, Any]]: ...

    # Incidents (R4-1)
    def open_incident(self, product: str, run_id: str, severity: str, summary: str, check_name: str = "") -> str | None: ...

    def resolve_open_incidents(self, product: str, run_id: str) -> None: ...

    def get_incidents(self, status: str | None = None, severity: str | None = None, limit: int = 50, offset: int = 0) -> list[dict[str, Any]]: ...

    def get_incident(self, incident_id: str) -> dict[str, Any] | None: ...

    def transition_incident(self, incident_id: str, status: str, actor: str, note: str = "") -> dict[str, Any] | None: ...

    def assign_incident(self, incident_id: str, owner: str, actor: str) -> dict[str, Any] | None: ...

    # SLA over time (R4-3)
    def get_sla(self, product: str, window_days: int = 30) -> dict[str, Any]: ...

    # Per-family rollup (R3-2)
    def get_object_family_status(self) -> dict[str, dict[str, dict[str, Any]]]: ...
