"""SQL-Dialekt-Adapter für den Result-Store (gemeinsamer Kern SQLite ⋂ HANA).

Der `ResultStore` (SQLite) und der `HanaStore` teilen sich denselben
Python-Code für Migrations-Lauf und die dialekt-sichere Kern-Tranche
(`packages/dq_core/store/base.py`); die *wenigen* Stellen, an denen sich die
SQL-Dialekte unterscheiden, kapselt dieses Modul — statt zwei Stores parallel
zu pflegen und auseinanderdriften zu lassen.

Bewusst klein gehalten: dank `hdbcli` und `sqlite3` denselben **qmark**-
Paramstyle (`?`) ist der Delta-Bereich überschaubar:

1. **DDL-Übersetzung** (`translate_ddl`) — Identitätsspalten, `TEXT`-Typen,
   `IF NOT EXISTS`.
2. **Upsert-Rendering** (`upsert`) — SQLite `INSERT OR REPLACE` vs. HANA `UPSERT`.
3. **Last-Insert-Id** (`last_insert_id`) — SQLite `cursor.lastrowid` vs. HANA
   `CURRENT_IDENTITY_VALUE()`.
4. **Fehler-Toleranz** beim Migrieren (`is_already_exists_error`).

`[SCHEMA-MAP]` Das Open-SQL-Schema wird **nicht** hier literalisiert, sondern
zur Laufzeit an der Verbindung gebunden (HanaStore `SET SCHEMA`), analog zum
Compiler. `[HANA-VERIFY]`-Marker kennzeichnen Übersetzungen, die gegen einen
echten Tenant zu verifizieren sind (Smoke-Harness, C4/L1).
"""
from __future__ import annotations

import re
from typing import Any, Protocol


class Dialect(Protocol):
    """Kapselt die dialekt-spezifischen SQL-Bausteine eines Store-Backends."""

    name: str

    def translate_ddl(self, sql: str) -> str:
        """Übersetzt eine (SQLite-formulierte) Migrations-Anweisung in den Zieldialekt."""
        ...

    def upsert(self, table: str, columns: list[str], pk_columns: list[str]) -> str:
        """Rendert ein Insert-or-Replace über den Primärschlüssel `pk_columns`."""
        ...

    def last_insert_id(self, cursor: Any) -> int:
        """Liefert die zuletzt generierte Identity-Id nach einem INSERT."""
        ...

    def is_already_exists_error(self, exc: Exception) -> bool:
        """True, wenn `exc` ein idempotenter „existiert bereits"-Fehler ist (Migration)."""
        ...


def _placeholders(n: int) -> str:
    return ",".join(["?"] * n)


class SqliteDialect:
    """SQLite — die Referenz. `translate_ddl` ist (nahezu) die Identität, da die
    Migrations-Dateien in SQLite-Syntax vorliegen."""

    name = "sqlite"

    def translate_ddl(self, sql: str) -> str:
        return sql

    def upsert(self, table: str, columns: list[str], pk_columns: list[str]) -> str:
        cols = ",".join(columns)
        return (
            f"INSERT OR REPLACE INTO {table} ({cols}) "
            f"VALUES ({_placeholders(len(columns))})"
        )

    def last_insert_id(self, cursor: Any) -> int:
        return int(cursor.lastrowid)

    def is_already_exists_error(self, exc: Exception) -> bool:
        msg = str(exc).lower()
        return "already exists" in msg or "duplicate column" in msg


class HanaDialect:
    """SAP HANA (Open-SQL, `hdbcli`).

    `[HANA-VERIFY]` Die DDL-Übersetzung deckt die in den Migrationen tatsächlich
    verwendeten Konstrukte ab (Identity-PK, `TEXT`, `IF NOT EXISTS`); die
    Ausführung gegen einen echten Tenant erfolgt über die Smoke-Harness
    (`tests/integration/test_hana_smoke.py`, `make hana-smoke`).
    """

    name = "hana"

    # Spalten, deren Inhalt (JSON/Freitext) die NVARCHAR-Obergrenze reißen kann
    # und die NICHT Teil eines PK/Index sind → NCLOB. `[HANA-VERIFY]`
    _LARGE_TEXT_COLUMNS = frozenset({
        "row_data", "result_json", "detail", "payload", "body", "message",
        "impacted_objects", "definition", "csn_projection", "config",
        "diff_json", "rca_json", "members", "sample_json", "columns_json",
    })

    _DEFAULT_NVARCHAR = 5000

    def translate_ddl(self, sql: str) -> str:
        out = sql
        # `CREATE TABLE/INDEX IF NOT EXISTS` → HANA kennt das nicht; der
        # Migrations-Runner überspringt bereits angewandte Versionen und toleriert
        # „existiert bereits" idempotent (is_already_exists_error).
        out = re.sub(r"\bIF\s+NOT\s+EXISTS\b", "", out, flags=re.IGNORECASE)

        # Identity-Primärschlüssel: `INTEGER PRIMARY KEY AUTOINCREMENT`
        #   → `INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`
        out = re.sub(
            r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            out,
            flags=re.IGNORECASE,
        )
        # Übrig gebliebenes nacktes AUTOINCREMENT (SQLite-only) entfernen.
        out = re.sub(r"\s+AUTOINCREMENT\b", "", out, flags=re.IGNORECASE)

        # TEXT-Spalten typisieren. Große JSON/Freitext-Spalten → NCLOB, sonst
        # NVARCHAR(n). Wir ersetzen `<name> ... TEXT` konservativ pro Zeile.
        out = self._map_text_types(out)

        # Doppelte Leerzeichen aus dem IF-NOT-EXISTS-Strip glätten.
        out = re.sub(r"[ \t]{2,}", " ", out)
        return out

    def _map_text_types(self, sql: str) -> str:
        def repl(match: re.Match[str]) -> str:
            col = match.group("col")
            large = col.lower() in self._LARGE_TEXT_COLUMNS
            typ = "NCLOB" if large else f"NVARCHAR({self._DEFAULT_NVARCHAR})"
            return f"{match.group('lead')}{col} {typ}"

        # Zeilenweise: „  <col>   TEXT" am Spaltenkopf. Vermeidet Treffer in
        # Kommentaren (die der Runner ohnehin strippt) und in Ausdrücken.
        pattern = re.compile(
            r"(?P<lead>^\s*)(?P<col>[A-Za-z_][A-Za-z0-9_]*)\s+TEXT\b",
            flags=re.IGNORECASE | re.MULTILINE,
        )
        return pattern.sub(repl, sql)

    def upsert(self, table: str, columns: list[str], pk_columns: list[str]) -> str:
        # HANA: UPSERT … VALUES … WITH PRIMARY KEY (nutzt den PK der Zieltabelle).
        cols = ",".join(columns)
        return (
            f"UPSERT {table} ({cols}) "
            f"VALUES ({_placeholders(len(columns))}) WITH PRIMARY KEY"
        )

    def last_insert_id(self, cursor: Any) -> int:
        # `[HANA-VERIFY]` hdbcli-Cursor führt kein lastrowid; die zuletzt in der
        # Session generierte Identity liefert CURRENT_IDENTITY_VALUE().
        cursor.execute("SELECT CURRENT_IDENTITY_VALUE() FROM DUMMY")
        row = cursor.fetchone()
        return int(row[0]) if row and row[0] is not None else 0

    def is_already_exists_error(self, exc: Exception) -> bool:
        msg = str(exc).lower()
        # HANA-Fehlertexte/-Codes für „existiert bereits" (Tabelle 288, Index 261).
        return (
            "already exists" in msg
            or "cannot use duplicate" in msg
            or "existing" in msg and "name" in msg
        )


SQLITE = SqliteDialect()
HANA = HanaDialect()
