"""SQL-Dialekt-Adapter (SQLite ⋂ HANA) — Übersetzung & Rendering (O6)."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parents[2] / "packages"))

from dq_core.store.dialect import HANA, SQLITE


def test_sqlite_is_identity_and_insert_or_replace():
    ddl = "CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY AUTOINCREMENT, a TEXT)"
    assert SQLITE.translate_ddl(ddl) == ddl
    assert SQLITE.upsert("t", ["a", "b"], ["a"]) == "INSERT OR REPLACE INTO t (a,b) VALUES (?,?)"


def test_hana_identity_pk_translation():
    out = HANA.translate_ddl(
        "CREATE TABLE IF NOT EXISTS t (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  a TEXT\n)"
    )
    assert "IF NOT EXISTS" not in out
    assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out
    assert "AUTOINCREMENT" not in out


def test_hana_text_type_mapping_nvarchar_vs_nclob():
    out = HANA.translate_ddl(
        "CREATE TABLE t (\n  run_id TEXT,\n  row_data TEXT,\n  note TEXT\n)"
    )
    # PK-/normale Textspalte → NVARCHAR; große JSON-Spalte → NCLOB.
    assert "run_id NVARCHAR(" in out
    assert "note NVARCHAR(" in out
    assert "row_data NCLOB" in out


def test_hana_upsert_uses_with_primary_key():
    sql = HANA.upsert("dq_runs", ["run_id", "dataset"], ["run_id"])
    assert sql == "UPSERT dq_runs (run_id,dataset) VALUES (?,?) WITH PRIMARY KEY"


def test_already_exists_error_tolerance():
    assert SQLITE.is_already_exists_error(Exception("duplicate column name: kind"))
    assert HANA.is_already_exists_error(Exception("table 'T' already exists"))
    assert not SQLITE.is_already_exists_error(Exception("syntax error near ,"))


def test_hana_partial_unique_index_becomes_generated_guard():
    # SQLite-Partial-Index → HANA generierte Guard-Spalte + Unique-Constraint.
    out = HANA.translate_ddl(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_dq_runs_one_running\n"
        "  ON dq_runs(dataset) WHERE run_state = 'running';"
    )
    assert "GENERATED ALWAYS AS" in out
    assert "CASE WHEN run_state = 'running' THEN dataset ELSE NULL END" in out
    assert "ADD CONSTRAINT idx_dq_runs_one_running UNIQUE" in out
    assert "CREATE UNIQUE INDEX" not in out  # kein gefilterter Index mehr


def test_unique_violation_detection():
    assert SQLITE.is_unique_violation(Exception("UNIQUE constraint failed: dq_runs.dataset"))
    assert HANA.is_unique_violation(Exception("unique constraint violated: idx (301)"))
    assert not SQLITE.is_unique_violation(Exception("no such table: dq_runs"))
    assert not HANA.is_unique_violation(Exception("invalid column name"))


def test_qmark_paramstyle_shared():
    # Beide Dialekte nutzen qmark (?) — der Grund, warum der Kern geteilt werden kann.
    assert "?" in SQLITE.upsert("t", ["a"], ["a"])
    assert "?" in HANA.upsert("t", ["a"], ["a"])
